/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyWaldosRouteImport } from './routes/myWaldos'
import { Route as FindWaldoRouteImport } from './routes/findWaldo'
import { Route as CreateAvatarRouteImport } from './routes/createAvatar'
import { Route as ChooseWaldoRouteImport } from './routes/chooseWaldo'
import { Route as BadWaldoRouteImport } from './routes/badWaldo'
import { Route as AskWaldoRouteImport } from './routes/askWaldo'
import { Route as IndexRouteImport } from './routes/index'

const MyWaldosRoute = MyWaldosRouteImport.update({
  id: '/myWaldos',
  path: '/myWaldos',
  getParentRoute: () => rootRouteImport,
} as any)
const FindWaldoRoute = FindWaldoRouteImport.update({
  id: '/findWaldo',
  path: '/findWaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAvatarRoute = CreateAvatarRouteImport.update({
  id: '/createAvatar',
  path: '/createAvatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseWaldoRoute = ChooseWaldoRouteImport.update({
  id: '/chooseWaldo',
  path: '/chooseWaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const BadWaldoRoute = BadWaldoRouteImport.update({
  id: '/badWaldo',
  path: '/badWaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const AskWaldoRoute = AskWaldoRouteImport.update({
  id: '/askWaldo',
  path: '/askWaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/askWaldo': typeof AskWaldoRoute
  '/badWaldo': typeof BadWaldoRoute
  '/chooseWaldo': typeof ChooseWaldoRoute
  '/createAvatar': typeof CreateAvatarRoute
  '/findWaldo': typeof FindWaldoRoute
  '/myWaldos': typeof MyWaldosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/askWaldo': typeof AskWaldoRoute
  '/badWaldo': typeof BadWaldoRoute
  '/chooseWaldo': typeof ChooseWaldoRoute
  '/createAvatar': typeof CreateAvatarRoute
  '/findWaldo': typeof FindWaldoRoute
  '/myWaldos': typeof MyWaldosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/askWaldo': typeof AskWaldoRoute
  '/badWaldo': typeof BadWaldoRoute
  '/chooseWaldo': typeof ChooseWaldoRoute
  '/createAvatar': typeof CreateAvatarRoute
  '/findWaldo': typeof FindWaldoRoute
  '/myWaldos': typeof MyWaldosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/askWaldo'
    | '/badWaldo'
    | '/chooseWaldo'
    | '/createAvatar'
    | '/findWaldo'
    | '/myWaldos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/askWaldo'
    | '/badWaldo'
    | '/chooseWaldo'
    | '/createAvatar'
    | '/findWaldo'
    | '/myWaldos'
  id:
    | '__root__'
    | '/'
    | '/askWaldo'
    | '/badWaldo'
    | '/chooseWaldo'
    | '/createAvatar'
    | '/findWaldo'
    | '/myWaldos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskWaldoRoute: typeof AskWaldoRoute
  BadWaldoRoute: typeof BadWaldoRoute
  ChooseWaldoRoute: typeof ChooseWaldoRoute
  CreateAvatarRoute: typeof CreateAvatarRoute
  FindWaldoRoute: typeof FindWaldoRoute
  MyWaldosRoute: typeof MyWaldosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/myWaldos': {
      id: '/myWaldos'
      path: '/myWaldos'
      fullPath: '/myWaldos'
      preLoaderRoute: typeof MyWaldosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findWaldo': {
      id: '/findWaldo'
      path: '/findWaldo'
      fullPath: '/findWaldo'
      preLoaderRoute: typeof FindWaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createAvatar': {
      id: '/createAvatar'
      path: '/createAvatar'
      fullPath: '/createAvatar'
      preLoaderRoute: typeof CreateAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chooseWaldo': {
      id: '/chooseWaldo'
      path: '/chooseWaldo'
      fullPath: '/chooseWaldo'
      preLoaderRoute: typeof ChooseWaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badWaldo': {
      id: '/badWaldo'
      path: '/badWaldo'
      fullPath: '/badWaldo'
      preLoaderRoute: typeof BadWaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/askWaldo': {
      id: '/askWaldo'
      path: '/askWaldo'
      fullPath: '/askWaldo'
      preLoaderRoute: typeof AskWaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskWaldoRoute: AskWaldoRoute,
  BadWaldoRoute: BadWaldoRoute,
  ChooseWaldoRoute: ChooseWaldoRoute,
  CreateAvatarRoute: CreateAvatarRoute,
  FindWaldoRoute: FindWaldoRoute,
  MyWaldosRoute: MyWaldosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
